---
debname: flux2
debver: 2.7.5-1
src_path: files
dl_files:
  flux_2.7.5_linux_amd64.tar.gz:
    topdir: null
    url: https://github.com/fluxcd/flux2/releases/download/v2.7.5/flux_2.7.5_linux_amd64.tar.gz
    sha256sum: 1e92141e8498289e4b27411385aeb18396053176cf297b0cb99abd6ca8293e75

revision:
  dist: $STX_DIST
  PKG_GITREVCOUNT: true
