---
debname: puppet-module-puppetlabs-postgresql
debver: 10.5.0-1
dl_path:
    name: puppet-module-puppetlabs-postgresql-10.5.0.tar.gz
    url: https://github.com/puppetlabs/puppetlabs-postgresql/archive/refs/tags/v10.5.0.tar.gz
    md5sum: 7ff2fb525537655e02abf15f5eea0079
    sha256sum: ffdaa433fa7b285949d0e38101d7b8816c10445f41a62ec9e63d122701c34d01
revision:
    dist: $STX_DIST
    PKG_GITREVCOUNT: true
