---
debname: puppet-module-nanliu-staging
debver: 1.0.4-3
dl_path:
  name: puppet-module-nanliu-staging-1.0.4-3.tar.gz
  url: https://salsa.debian.org/openstack-team/puppet/puppet-module-nanliu-staging/-/archive/debian/1.0.4-3/puppet-module-nanliu-staging-debian-1.0.4-3.tar.gz
  md5sum: b45e81281b2dcbaf100190f4d05141e0
  sha256sum: cfdd0a88be741f039cce7b8827d619c3246c94343ad168b4c9b50419739fdc73
  dist: $STX_DIST
  PKG_GITREVCOUNT: true
