---
debname: facter
debver: 4.10.0-1
dl_path:
  name: facter-4.10.0-1.tar.gz
  url: https://salsa.debian.org/puppet-team/facter/-/archive/debian/4.10.0-1/facter-debian-4.10.0-1.tar.gz
  md5sum: eb38e9282403289cc59f5defc5ecb1f8
  sha256sum: b2e760cdfc2aa5113c270cd981dc9eec690ea1956576655c9ddcd4ab6d0e793b
revision:
  dist: $STX_DIST
  PKG_GITREVCOUNT: true
