---
debname: puppet-module-asciiduck-sssd
debver: 0.3.0-1.1
archive: https://snapshot.debian.org/archive/debian/20250901T022746Z/pool/main/p/puppet-module-asciiduck-sssd/
revision:
  dist: $STX_DIST
  PKG_GITREVCOUNT: true
