---
debname: python3-kubernetes
debver: 34.1.0
dl_path:
    name: python3-kubernetes.34.1.0.tar.gz
    url: https://github.com/kubernetes-client/python/archive/refs/tags/v34.1.0.tar.gz
    sha256sum: 39f9fc9d4662c44ba5ddf1104a1000cbc7e16ae605cd906d56f0bee83211ce93
revision:
    dist: $STX_DIST
    GITREVCOUNT:
        BASE_SRCREV: 310ac64ec5ec83206103422ef6820282acb3f472
        SRC_DIR: ${MY_REPO}/stx/integ/kubernetes/python3-kubernetes
