debver: 1.22.5
dl_path:
  name: kubernetes-1.22.5.tar.gz
  url: https://github.com/kubernetes/kubernetes/archive/refs/tags/v1.22.5.tar.gz
  md5sum: 98a8b8b66557a7c4cdf79533c2cc77fc
  sha256sum: 9ea0605901282e280b500f22a10f5428ef9c874ad55ad6c2aa1eb7bd71686606
revision:
  dist: $STX_DIST
  PKG_GITREVCOUNT: true
