---
debname: puppet-module-openstacklib
debver: 17.4.0-2
dl_path:
  name: puppet-module-openstacklib-17.4.0-2.tar.gz
  url: https://salsa.debian.org/openstack-team/puppet/puppet-module-openstacklib/-/archive/debian/17.4.0-2/puppet-module-openstacklib-debian-17.4.0-2.tar.gz
  md5sum: b7509751fe173ba20555859186fae36b
  sha256sum: fbef49106a09304665b6628b9a0c5ebd08d6b9e3084535d8c138d70fc3ed46ec
revision:
  dist: $STX_DIST
  PKG_GITREVCOUNT: true
