---
debname: helm
debver: 3.19.2-1
src_path: files
dl_files:
  helm-v3.19.2-linux-amd64.tar.gz:
    topdir: linux-amd64
    url: https://get.helm.sh/helm-v3.19.2-linux-amd64.tar.gz
    sha256sum: 2114c9dea2844dce6d0ee2d792a9aae846be8cf53d5b19dc2988b5a0e8fec26e

revision:
  dist: $STX_DIST
  GITREVCOUNT:
    BASE_SRCREV: f98b1a5b40c01f54e407d1aaa1a5945c6beeb6c5
