---
debname: puppet-module-oslo
debver: 25.0.0-2
dl_path:
  name: puppet-module-oslo-25.0.0-2.tar.gz
  url: https://salsa.debian.org/openstack-team/puppet/puppet-module-oslo/-/archive/debian/25.0.0-2/puppet-module-oslo-debian-25.0.0-2.tar.gz
  md5sum: 6c83aa05dae4feafcc3ab325b2e78f96
  sha256sum: 1405a45237ff7ef70f47dcc8de60e9b8ed1f695e0f9e684b3a5c9879ce89d58f
revision:
  dist: $STX_DIST
  PKG_GITREVCOUNT: true
