---
debver: 1.31.5
dl_path:
  name: kubernetes-1.31.5.tar.gz
  url: https://github.com/kubernetes/kubernetes/archive/refs/tags/v1.31.5.tar.gz
  sha256sum: 7648c290f46bfc45cb8a24dc94e39cdea333bbe39223ab1cc253ebf9e2e0c3cb
revision:
  dist: ${STX_DIST}
  GITREVCOUNT:
    BASE_SRCREV: 7c7e41685ac12c72d667c375f477598d70a4cca6
    SRC_DIR: ${MY_REPO}/stx/integ/kubernetes/kubernetes-1.31.5
