---
debname: runc
debver: 1.1.7
src_path: null
dl_files:
  runc.amd64:
    topdir: null
    url: https://github.com/opencontainers/runc/releases/download/v1.1.7/runc.amd64
    sha256sum: c3aadb419e5872af49504b6de894055251d2e685fddddb981a79703e7f895cbd
revision:
  dist: $STX_DIST
  GITREVCOUNT:
    BASE_SRCREV: fe5768d72e8ad2f1d780cfaab11294998d5ed377
    SRC_DIR: ${MY_REPO}/stx/integ/kubernetes/runc
